### ISSUE TITLE
Speedup Dataset Loading 

### ISSUE THREAD

**Issue by aaron-sandoval** [understanding-search/maze-dataset#24] opened 2024-02-04 20:07 UTC
Datasets are slow to load from disk because each maze is written in its own numpy arrays. This could be accelerated by concatenating the numpy arrays for all mazes.

**Comment by mivanit** [comment] 2024-02-04 20:21
my bad, this is a duplicate of #18. closing.

**Closed by mivanit** 2024-02-04 20:21 UTC
Labels: enhancement, code-quality
